resources:
- namespace.yml
- frontend-deployment.yaml
- frontend-service.yaml
- ingress.yaml


commonAnnotations:
  app: demo
  
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app: demo