resources:
- backend-deployment.yaml
- backend-service.yaml


commonAnnotations:
  app: demo
  
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app: demo